source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'Sample' do
  use_frameworks!

  ## Tool
  pod 'AcknowledgementsPlist', '0.0.4'

  ## UI
  pod 'AttributedLabel', '2.0.0'
  pod 'Reusable', '4.0.5'

end
