source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'

target 'Sample' do
  use_frameworks!

  ## Tool
  pod 'AcknowledgementsPlist'

  ## UI
  pod 'AttributedLabel'
  pod 'Reusable'

end
